### ISSUE TITLE
Add PSR-7 TagHandler::tagResponse()

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#230]
Currently, we only have `tagResponse()` in the bundle (for Symfony responses). Now PSR-7 has been accepted, however, we could also add this method to the library, setting tags on a PSR-7 response. 

It’s then up for debate whether we want to override this in the bundle, or use Symfony’s PSR-7 bridge to convert between the two response types.

**Comment by dbu** [comment]
ah, indeed. this will become tricky with type hinting in the method
however. best would be if we find a way that works for both PSR 7 and
symfony. in a non-surprising way. maybe no typehint but instanceof checks?

**Comment by ddeboer** [comment]
Well, so far the library does not depend on Symfony requests/responses. I suggest we keep it that way and implement `tagResponse()` in the library (PSR-7 response) and override/decorate it in the bundle (Symfony response).

**Comment by dbu** [comment]
agreed. but we need to not have a type hint on `tagResponse` or we get
into a conflict with
https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/blob/master/Handler/TagHandler.php#L20
(will need to change the bundle method signature too, of course).

then in the bundle we check instanceof symfony Response and if so handle
it, otherwise call the lib, which checks instanceof psr7 Response and
handles or fails on anything else.
