### ISSUE TITLE
[cache tagging] http_resp_hdr_len check

### ISSUE THREAD

**Issue by wickedOne** [FriendsOfSymfony/FOSHttpCache#269]
in order to prevent the [tag expression](https://github.com/FriendsOfSymfony/FOSHttpCache/blob/f9769032eb43f6d1396cb60cf03550ea99257e60/src/ProxyClient/Varnish.php#L108) to exceed the configured [http_resp_hdr_len](https://www.varnish-cache.org/docs/3.0/reference/varnishd.html) value, i've implemented a check which will invalidate the tags in chunks if applicable.

would you guys be interested to have that in this library?

**Comment by dbu** [comment]
ups, yes that is a good idea. do you simply call ban() in a loop when things get too long? glad for a pull request, which imho could even go against the 1.3 branch as its essentially a bugfix.

**Comment by wickedOne** [comment]
yes, that's basically it.
currently it's like this (in an extend of the ``TagHandler`` from the ``FOSHttpCacheBundle``):

``` php
    /**
     * {@inheritdoc}
     */
    public function invalidateTags(array $tags)
    {
       if (mb_strlen(implode('|', $tags)) >= self::HTTP_RESP_HDR_LEN) {
            $tagsize = max(array_map('mb_strlen', $tags));
            $elems = floor(self::HTTP_RESP_HDR_LEN / $tagsize);

            foreach (array_chunk($tags, $elems) as $tagchunk) {
                parent::invalidateTags($tagchunk);
            }
        } else {
            parent::invalidateTags($tags);
        }
    }
```
which is not entirely accurate as it's basing it's chunks on the biggest tag size and the implode does not excatly match the header being sent.

of course that could be improved in a pull request for this library…

**Comment by dbu** [comment]
please do a pull request.

i guess most of the time, people will have few tags, so performance for
those does not matter much. i see 3 options:

1. what you do now. it is uncomplicated and only non-ideal if tags are
very different in length. (btw, if they are all the exact same length, i
think the added `,` would make the header too long... the shorter the
tags, the more. we should compensate for that.)

2. skip the initial implode and directly chunk - probably into a single
chunk.

3. do not use implode but a loop of `$tags .= ','.$tag;` and count the
strlen up until the next tag no longer fits, at that point start the
next header. that would be most efficient with requests.


ideally we would have an idea of the performance of the different
approaches. if you want to have a look at that, maybe phpbench could
help. otherwise i think we can just go with 1) because for the typical
case of needing only one request, there will be no notable performance
difference.


if a single tag is extremely long, this is a problem in many ways (also
matching efficiency on varnish will suffer. maybe we want to check both
while tagging and while invalidating whether a tag is longer than an md5
hash and if so use the md5 instead, to cap the length? that would best
be a separate PR to keep things small and manageable.

**Comment by wickedOne** [comment]
thanks for the feedback!
will try to give the above a try probably somewhere next week as i'm currently short on time…

**Comment by dbu** [comment]
great!

**Comment by wickedOne** [comment]
phpbench results for the various strategies your described (and in the same order) using a tag array with 5000 tags of 15 bytes each:
```bash
+---------------------+------------------------+-------+--------+------+-----+------------+-------------+-------------+-------------+-------------+----------+--------+---------+
| benchmark           | subject                | group | params | revs | its | mem        | best        | mean        | mode        | worst       | stdev    | rstdev | diff    |
+---------------------+------------------------+-------+--------+------+-----+------------+-------------+-------------+-------------+-------------+----------+--------+---------+
| TagInvalidatorBench | benchInvalidateChunks  |       | []     | 1000 | 5   | 2,147,632b | 2,225.302μs | 2,253.501μs | 2,232.427μs | 2,339.079μs | 43.112μs | 1.91%  | +12.85% |
| TagInvalidatorBench | benchInvalidateChunk   |       | []     | 1000 | 5   | 2,147,632b | 2,223.412μs | 2,226.716μs | 2,225.110μs | 2,233.387μs | 3.615μs  | 0.16%  | +11.51% |
| TagInvalidatorBench | benchInvalidateForEach |       | []     | 1000 | 5   | 1,488,648b | 1,939.038μs | 1,996.856μs | 1,953.818μs | 2,137.796μs | 77.945μs | 3.90%  | 0.00%   |
+---------------------+------------------------+-------+--------+------+-----+------------+-------------+-------------+-------------+-------------+----------+--------+---------+
```
if you want more specifics just let me know…
