### ISSUE TITLE
Make Tagging an explicit responsiblity of the ProxyClient / next release?

### ISSUE THREAD

**Issue by dantleech** [FriendsOfSymfony/FOSHttpCache#283]
<strike>Actually we use the Ban capability of a proxy server to invalidate tags - in the [tag manager]() we send a regex to the proxy client for banning.</strike>

<strike>This causes problems for a proxy client which does not support ban, but does support tag invalidation as it should actually be passed a discrete list of tags, not a regex.</strike>

<strike>I suggest introducing a `TagInterface` in addition to `BanInterface`. The Varnish proxy client would then implement the`TagInterface` and subsequently perform the required BAN. Whereas another implementation (e.g. Symfony HTTP cache) can explicitly handle the tag invalidation.</strike>

This seems to be addressed in master -- do we know when the next release will be? Is anything standing in the way?

**Comment by dbu** [comment]
the main roadblock for the release was that we wanted to base the client on Httplug instead of tying us to a specific version of guzzle or other HTTP client. which got me sidetracked into Httplug rather deeply :-)

this now out of the way, i think we should be able to wrap up. the discussion around tagging with magnus and #253 is now the only major blocker.
