### ISSUE TITLE
Symfony HTTP Cache / Tag Invalidation

### ISSUE THREAD

**Issue by dantleech** [FriendsOfSymfony/FOSHttpCache#286]
Currently this library contains several classes related to extending the Symfony HTTP Cache by way of an EventDispatchingKernel trait.

There is a general need to implement tag invalidation with the Symfony HTTP cache, and this has been done [here](https://github.com/dantleech/sf-http-cache-tagging/tree/master/src).

Most of the logic in that package is concerned with tags and @magnusnordlander is proposing to create a [new package](https://github.com/php-tag-store/php-tag-store) which is dedicated to tag storage. Therefore the amount code required for adding the tagging functionality to the HTTP cache is not very large.

We could therefore reasonably add the tagging functionality in this package, however I am not so sure that it belongs here -  
- I believe all of the functionality we add to the Symfony HTTP Cache can be used without the infrastructure of the FOSHttpCache.
- I think this bundle should _integrate_ with third-party caches and not provide solutions itself.

I therefore propose to create a new package containing to the Symfony HTTP cache and ultimately remove the `SymfonyCache` namespace from this package.

wdyt?

**Comment by dbu** [comment]
i think this is the right direction to go. 

so we would create a package for the event handling http cache without implementations?
and one for HttpCache tags? there are a couple of other events besides tags, like purge and refresh. where would those fit?

**Comment by andrerom** [comment]
Fine with me as long as it remains transparent for users:
- responses needs to be the same, standardized tagging header *(& user context header, but digress)*
- ProxyClient API needs to be same across Sf, Varnsih, Akamai .. *(purge/refresh/expire/expireByTag)*

**Comment by dantleech** [comment]
> so we would create a package for the event handling http cache without implementations?

I was thinking more of a single HTTPCache package with all of the features that we provide here, including the forthcoming tagging. I would think that would be easier to maintain and document etc - otherwise we should consider a new organization and have separate packages for each feature, but I don't personally think that its worth it.

> responses needs to be the same, standardized tagging header

Yeah, see no reason why we would change that.

> ProxyClient API needs to be same across Sf, Varnsih, Akamai

I imagine the ProxyClient would staying here and the proposed package would be just another third-party that we integrate with.

**Comment by dbu** [comment]
i don't think we should micro-split features i think. the only question for me is if we want to split the event emitting trait out into a separate library. but on the other hand we can still do that when people ask for it and keep things simple for now.

we could add this in the organization that @magnusnordlander created, maybe?

**Comment by dantleech** [comment]
Do you mean the `php-tag-store` organization? not sure that is the most appropriate, I think about it being in FOS. It is actually directly related to a symfony component after all.

**Comment by dbu** [comment]
> Do you mean the |php-tag-store| organization? not sure that is the most
> appropriate, I think about it being in FOS. It is actually directly
> related to a symfony component after all.

hm, true that. what name do you propose?

**Comment by dantleech** [comment]
Maybe one of:

- `FOSSymfonyHttpCache`
- `FOSHttpKernelCache` 

We could maybe suffix it with `Extensions` or `Extra`, but equally the name could be a reference to the EventDispatchingKernel itself, whereby it would make sense without a suffix.

**Comment by dbu** [comment]
while |FOSSymfonyHttpCache| is a bit hard to type with tripple S, i
think its the semantically correct name. lets try that. do you want to
create the issue to request permission to create this repo?

the procedure is to create an issue at
https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues
and describe what you want to do. maybe you can summarize the discussion
from this thread so people don't need to read up the whole discussion to
decide...

**Comment by dantleech** [comment]
Done: https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/57

**Comment by dbu** [comment]
symfony 3.2 will have cache tagging built into the cache component: https://github.com/symfony/symfony/pull/19047

maybe we could provide a StoreInterface implementation that uses the cache adapter and extracts tags from the response. and an additional method to invalidate tags. that would keep the effort to support tags relatively small and would probably fit into this library.

**Comment by andrerom** [comment]
I have been thinking in similar direction latly, that we probably need to simplify the 2.0 efforts a bit to unblock it, by taking advantage of Symfony Cache Component as of 3.2, and on Varnish side we can improve what we have by adding support for [xkey](https://github.com/varnish/varnish-modules/blob/master/docs/xkey.rst).

**Comment by dbu** [comment]
i talked with magnus and he said he won't have time soon to contribute his refactoring ideas. so indeed we should wrap up what we have and get a version out. tagging with HttpCache could also be 2.1, it should not need a BC break.

xkey sounds cool. by default, i don't want us to force the users to install an extension. but if i see it correctly, this can be supported purely by documentation. the tagging works exactly the same as usually, just configure the tag header to `xkey`. invalidating means that the vcl would need to detect if the ban request has tags and then call the xkey function instead of doing a ban. did you play with it? can you contribute a documentation section for it?

**Comment by andrerom** [comment]
> invalidating means that the vcl would need to detect if the ban request has tags and then call the xkey function instead of doing a ban. 

Or we need to support this in `Varnsih->invalidateTags()` where it is doing a ban which does all sorts of magic on the tags making it tedius in the vcl to undo that.

Open question is if it supports soft purging several tags at once, does not look like it, but maybe there is a way.

> did you play with it?

no

**Comment by dbu** [comment]
ah right, it transforms the list of tags into a regular expression. then yes, it should be a different variant of the client. actually this is a different topic than this issue. best track it in a separate github issue.

**Comment by dbu** [comment]
@andrerom would you be interested in starting and maintaining the symfony cache extensions as a separate FOS library? the thing we discussed at https://github.com/FriendsOfSymfony/friendsofsymfony.github.com/issues/57 . there where no vetos, but nothing happened yet and we would best have 2 people volunteering to invest time into this. (dan and you - i am happy to help with questions but my focus is on the cache invalidation in general and varnish and nginx, rather than the symfony httpcache.)

**Comment by andrerom** [comment]
Unsure, cause in the meantime we started go our own way for now as we still had our own abstraction layer around where we where are able to add some features _(very WIP here for those interested: https://github.com/ezsystems/ezpublish-kernel/pull/1772)_.

For long term, given outcome of https://github.com/symfony/symfony/issues/19705, and given Symfony now has a Cache component cable of better expiry, several adapters and builtin tagging as of 3.2. A better scenario would be if we agree with core team and other interested community members to move some of these features into Symfony. As in:
1. Change upstream Symfony Proxy to use Symfony Cache to better support expiry and support for several adapters
2. Better debug support upstream
3. Figure out if purging can somehow be moved into upstream, if so it can take advantage of tagging from Symfony Cache and aim to support use of xkey on Varnish for the same there, otherwise we keep this here and can simplify thanks to 1.
4. If purging is moved upstream remaining question would be if UserContext can make sense there to

**Comment by dbu** [comment]
if we can move things upstream, that is indeed the best solution. can you
drive this effort? i am happy to support where needed.

moving upstream will take some time. meanwhile, would you vote to keep the
cache kernel in here or move it out to make the transition simpler once
symfony is ready? as we will need to keep some things - at least the
invalidation client - outside symfony core, it might be better to not split?

**Comment by andrerom** [comment]
"cache kernel" => Sf HttpCache proxy?

No strong opinions on it, I'm fine with either _(but see below)_

> can you drive this effort?

I wish, but we might have someone on our team that can soon

**Comment by dbu** [comment]
yep, i meant HttpCache.

@dantleech how do you think about this? should we move it out, or keep it in here and see if most of the logic can be moved to symfony/symfony ?

**Comment by dbu** [comment]
looking at PSR-6 and the HttpCache in the HttpKernel package (note that the FrameworkBundle kernel does not allow passing the store instance, but the base class in kernel does), i think it should be possible to provide a StoreInterface implementation that builds on PSR-6 instead of implementing a filesystem cache itself. the lock part is the trickiest. my idea would be to solve it with storing [requesthash].lock cache entries. for `cleanup` we would however need the cache tag or hierarchical cache decorator to find all locks. the problem with that is that we would need to introduce a dependency on `cache/taggable-cache` in the place where we define the store. @nicolas-grekas i fear that additional dependency inside symfony would not be welcome, would it? or do you have an idea how we can solve the lock operations differently?

if we have tagging anyways, we could add a TaggableStoreInterface that extends StoreInterface with a method to invalidate by tag. another question is how we would write the tags from the HttpCache, as StoreInterface.:write does only accept request and response. should we set the tags as information on response and have the store look at the response for this?

**Comment by nicolas-grekas** [comment]
Since SF3.2 has tag support, why would we need cache/taggable-cache for? About locks, did you look at the PR for a new Lock component? Would it help?

**Comment by dbu** [comment]
> Since SF3.2 has tag support, why would we need cache/taggable-cache for?

hm, where is the tag support located? looking into the symfony/cache
component, i find no mention of "tag". what we want to do is add tags to
cache entries so that we can later invalidate all cached responses that
had some tag on them.

> About locks, did you look at the PR for a new Lock component? Would it help?

ah, https://github.com/symfony/symfony/pull/21093 would be an idea, to
store locks with a dedicated tool. the proposal looks more complicated
than what we currently do, but getting a reliable lock system would be
worth that. and it supports shared backends as well. we would then need
to build the store with both a psr-16 cache and a lock service, but that
sounds ok.

however, i don't see a method in
https://github.com/symfony/symfony/pull/21093 that would allow to
cleanup all existing locks. or can the lock component handle "session
locks" that expire when the process that created them ends? if it does,
that would actually be the better solution and we could implement
cleanup as an empty method and deprecate it.

**Comment by nicolas-grekas** [comment]
https://symfony.com/blog/new-in-symfony-3-2-tagged-cache

**Comment by dbu** [comment]
oh well... sorry! i had two checkouts of symfony/symfony on my computer.
i updated one, and then browsed the other one. that looks really
promising, we can then just depend the http-kernel on symfony/cache, i
hope that is ok.

thanks for the pointers!

**Comment by jderusse** [comment]
> however, i don't see a method in
symfony/symfony#21093 that would allow to
cleanup all existing locks. or can the lock component handle "session
locks" that expire when the process that created them ends? if it does,
that would actually be the better solution and we could implement
cleanup as an empty method and deprecate it.

In fact, the Lock component (at least my proposal) is designed to couple the lock with the process who acquired it. If the process died without releasing the lock (bug or segfault), then the lock is automaticaly released. You don't need to cleanup.

It's handled in differents way by the stores:
* flockStore uses [flock](http://php.net/manual/en/function.flock.php) which let the kernel to release the resource when the process died
* semaphoreStore uses [sem_acquire](http://php.net/manual/en/function.sem-acquire.php)  for the same goal
* redisStore use a TTL mechanism to release the lokc when it expires
* memcachedStore same as redis

nb: flockStore creates empty files and don't delete it (because of race condition they can't be safly deleted), which can create a lot of inode if you create a lot of different locks.

**Comment by dbu** [comment]
>   * flockStore uses flock <http://php.net/manual/en/function.flock.php>
>     which let the kernel to release the resource when the process died
>   * semaphoreStore uses sem_acquire
>     <http://php.net/manual/en/function.sem-acquire.php> for the same goal
>   * redisStore use a TTL mechanism to release the lokc when it expires
>   * memcachedStore same as redis
> 
> nb: flockStore creates empty files and don't delete it (because of race
> condition they can't be safly deleted), which can create a lot of inode
> if you create a lot of different locks.

so the most stable proposition would be semaphoreStore because it does
not leave lock files lying around and does not have to guess with cache
lifetimes? i would make this configurable but would have to use one as
default.

is there an ETA when the lock component will be merged?

**Comment by jderusse** [comment]
Depends of the usage. For local concurrency use semaphore (if available). 
For remote (multi servers) use redis/memcached with a fine tuned TTL.

**Comment by dbu** [comment]
@nicolas-grekas any idea if/when the lock component will be merged?

**Comment by Toflar** [comment]
For the record: The lock component is there and [this PR](https://github.com/symfony/symfony/pull/20061) might be interesting.

**Comment by dbu** [comment]
indeed!

**Comment by Toflar** [comment]
The PR has been closed and Fabien mainly argued against it because it was a pure PSR-6 implementation allowing any cache back end to be used while only the filesystem one makes sense. Imho the same applies for the locking process. Only file locking really makes sense here.
I'm still kind of convinced that adding support for tagging makes sense for Symfony's `HttpCache`. E.g. I can imagine it to be a requirement for an application to even make it work. A good application should set out for excellent caching and tagging is often required so even if you don't expect too much traffic you would need to set up Varnish atm because it's the only one that supports tagging (in this lib, I mean). That's why I still consider this to be a valuable feature. It allows to start off small and move to better alternatives once required.
I think the way to go here to add support for tagging is to add our own store that implements the `HttpCache\StoreInterface` and uses both, the Cache and the Lock components internally but hardcoded to the respective file adapters so you cannot use Redis and Co.
Thanks to having most of the more complex stuff (locking, tagging) in Symfony 3.4 components that should end up being one rather simple class only (except for tests obviously) so I'm not sure it should be in its own library as @dantleech suggested long ago. I'd rather have it in this library which would, however, increase the minimum version of Symfony to 3.4 (or we add some check and document that if you want to use that feature you need SF 3.4). Wdyt?

**Comment by andrerom** [comment]
+10, even if the end goal would be to Symfony Http cache to use Cache component and nativly support tagging, that might not happen just yet unless someone works on it.

>  increase the minimum version of Symfony to 3.4

if that is for tagging 3.2 should be ok as well right? that said, eventually 3.4 is the only one supported so not much of a differance.

**Comment by Toflar** [comment]
I guess I'll work on a PR here as soon as I find some time. Then we have some code we can discuss on 😄

**Comment by dbu** [comment]
i agree. why would we require symfony 3.4? do the older versions of cache / locking not work? if we require each of these component at the version where they have been added to symfony, it should even install in parallel with symfony/symfony (e.g. you can have symfony/symfony: 2.7.* + symfony/cache: 3.1.*).

i also notice that we only suggest the symfony/http-kernel and don't depend on it. (because the whole symfony cache support is only a part of this library.). i think we should do the same with these libraries. 

all in all it could make sense to move all symfony cache support into its own library and use proper dependencies rather than the "optional dependencies" we currently do. but its also complicating things, so i am fine with adding it in here and having some more suggested dependencies.

**Comment by Toflar** [comment]
> why would we require symfony 3.4? do the older versions of cache / locking not work?

Cache and tagging would be 3.2 but the lock component is in master only. I mean, file locking is not too hard to implement but why bother if there will be a component for that in the future? :)

> all in all it could make sense to move all symfony cache support into its own library and use proper dependencies rather than the "optional dependencies" we currently do.

That's true but dependency hell is increasing with every new library. As I said, this should end up being one class only and we can add two `class_exists()` in the constructor and throw an exception if the deps do not match. Eventually we might raise the minimum required versions, clean up, maybe release a new major version and also drop these checks.

**Comment by dbu** [comment]
yep, lets ride with those versions then, and have them as optional dependencies. and yes, lets add a check to the respective class/trait to throw a user friendly exception.

**Comment by Toflar** [comment]
It was just too tempting to work on it: https://github.com/FriendsOfSymfony/FOSHttpCache/pull/373

**Comment by Toflar** [comment]
@dbu I think this can be closed too :)

**Comment by dbu** [comment]
i will close it when we merge #376 ;-)
