### ISSUE TITLE
Varnish 5 compatibility

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCache#319]
[Varnish 5](https://www.varnish-cache.org/docs/trunk/whats-new/index.html) was released last month. “All users on 4.1 should be able to upgrade to this version without trouble”: this sounds hopeful. :wink:
- [ ] test against Varnish 5 on Travis
- [ ] make necessary changes to the VCLs that we ship (if necessary)
- [ ] update docs

**Comment by dbu** [comment]
good point. @ddeboer do you have time to do that? if we can sneak it in for 2.0, that would be nice!

how do we go about naming the files? should we start naming the vcl folder varnish4AndNewer or something like that? 4plus is not good because the commercial varnish license is called "Varnish Plus"

if we really need no changes, i'd prefer to not duplicate the vcl

**Comment by ddeboer** [comment]
I’ll try to find some time. If necessary, this can be added after 2.0.

How do you feel about dropping support for Varnish 3, which is [EOL](http://www.varnish-cache.org/releases/)?

**Comment by dbu** [comment]
i'd love to decide how we handle naming before we release 2.0. if the
vcl work for varnish 5, calling the folder varnish4 is odd. renaming
that is only possible if we do it before the release...

i'd prefer to keep varnish 3 around a bit. the opportunity cost is low,
as its only the vcl that is different. for new features like the
varnishadm proxy client, i would ignore varnish 3 however.
