### ISSUE TITLE
ProxyClient interface to differ between purge & expiry (soft purge)?

### ISSUE THREAD

**Issue by andrerom** [FriendsOfSymfony/FOSHttpCache#385]
> soft purge: Expiry of cache content on Reverse Proxy allowing a given amount of staleness either configured (VCL,..), or defined in [http headers](https://tools.ietf.org/html/rfc5861) like `stale-while-revalidate` and `stale-if-error`.

Hard vs soft purge often depends on the context of the domain, some cases it's soft purge is fine, and others not.

So unlike in #332 where I suggest using soft purge by default for tag invalidation, perhaps we should rather aim for the following over time:
- Domain code should be able to specify/hint if something can be safely expired _(soft purge)_
  - This goes for purge by url and by tag(s)
- Either implementation might not support it, or integrator might opt out from soft purge for whatever reason in config/VCL, in both cases fall back for expiry should be hard purge.

Technically there is nothing stopping us from using different headers for instance to differ soft purge from hard purge and handle it appropriately in VCL. I would assume the same can be made true with Symfony Proxy Cache over time.

**Comment by dbu** [comment]
yeah i think this is a distinction that did not exist yet in varnish when we originally started the implementation. it does make sense to me. i think the way to go would be adding a new interface for expiry with an expire method, with the same semantics as purge. its then up to each caching proxy client to decide how to best communicate it. i would leave it to the application that is using the httpcache to choose whether to use hard purge or soft expire.

at least in varnish, tags are not purged but banned, meaning they are marked as not valid anymore. so that would probably be a configuration for the proxy client to define if tags are expired or purged.

**Comment by andrerom** [comment]
> at least in varnish, tags are not purged but banned,

that's only true until xkey is merged, the context here is to think about how to better expose these options after that.

**Comment by dbu** [comment]
ah right. ok, then depending on whether xkey support is enabled, the varnish client can also allow expiring tags instead, all the better. but i would configure that on the proxy client level i think.

**Comment by dbu** [comment]
do we need to keep this issue open or are you ok with this?

**Comment by andrerom** [comment]
I'm ok with what we ended up with for now.
