### ISSUE TITLE
Varnish Cpu efficiency with CacheTags 

### ISSUE THREAD

**Issue by olivierHa** [FriendsOfSymfony/FOSHttpCache#393]
Hello, 

I've noticed that this library is appending "(,.+)?$" when submitting BAN to Varnish : 

https://github.com/FriendsOfSymfony/FOSHttpCache/blob/ecc458282b8a6f75387c3cb4705615b0f5b6d6a8/src/ProxyClient/Varnish.php#L73

But on Varnish side the BAN is called using a regex : 

https://github.com/FriendsOfSymfony/FOSHttpCache/blob/master/resources/config/varnish/fos_ban.vcl#L22

Is there any reasons to add such a suffix ?

Regards

Olivier

**Comment by dbu** [comment]
yes, the trailing comma or end of string is required to avoid accidental invalidation on partial matches. if there are the tags foo and foobar, invalidating with only the string "foo" would also invalidate the tag "foobar".

but looking at that expression, i think that we should instead match on `'(%s)(,|$)'`. then we don't need to match the whole tag header, in case those are long. do you want to try a pull request for that?

there is also work on supporting the varnish xkey module, which would be a much more efficient way to handle tags, as it would be purges instead of bans. see #332 for that topic (it needs some effort in figuring out how to test it, if you want to help make it happen)

**Comment by olivierHa** [comment]
Thanks for this quick reply. I understand better the end of the x-cache-tag expression :+1: 

I will try to submit a PR
