### ISSUE TITLE
Caching content for mini groups of several users behind firewall with tags

### ISSUE THREAD

**Issue by kmadenski** [FriendsOfSymfony/FOSHttpCache#486]
Hi guys. 
I found this advice in docs:
[If every user has their own hash, you probably don’t want to cache at all. **Or if you found out its worth it, vary on the credentials and don’t use the context hash mechanism.**](https://foshttpcache.readthedocs.io/en/latest/user-context.html#user-context)

Can u tell me more about this concept?

We have private API with multiple user teams. In one team we have 1-10 users and in which team all users has same content. 
80% of resources are edited very rarely (1 per year)

Searching for some speed up for our case.

**Comment by Toflar** [comment]
You need to identify what causes the content of your app to vary. Usually it's the same if the users have the same permissions. That's when the user context hash is a good choice. It's basically one variant per permission combination.

But if your content varies for every user (e.g. displaying the user's age, username etc.) you don't want to cache at all because you would create a cache variant for every user which will usually just blow your cache storage up.

But as usual, it really depends...

**Comment by dbu** [comment]
if you have individual content, you can use the cache headers to have the browser cache content. the only edge case i can think of is if you do ESI and want to cache the individual things as well because they are heavy and don't constantly change.

if you want to cache per team, you could look into the user context mechanism (explained in the documentation), and have a thing that builds the hash depending on those teams (if you do symfony, you might use a role to identify the team, and make the hash based on the roles of the user). then you end up with one cache per team...
